version: '3.3'

services:
  redis:
    image: redis:alpine3.20
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /root/redis:/root/redis
    environment:
      - REDIS_PASSWORD=example_password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  redisinsight:
    image: redis/redisinsight
    restart: always
    ports:
      - "5540:5540"